### PR TITLE
Removed build containers from `docker-compose.yml` in favour of separate commands

### PR DESCRIPTION
**Pull request by Silic0nS0ldier**
I've been waiting to get this together for awhile now, but just needed to work out the kinks.

I've removed some redundancies in the documented installation process for Docker, and removed the composer and node services (`docker-compose` is not intended to be used like that).

Will need someone to verify the updated commands work in bash, as they were developed in within PowerShell and git bash wasn't playing with Docker very well.

### CODE REVIEW

**Comment by Silic0nS0ldier** [comment]
Ugh, build errors are caused by composer failing on the PHP v5.6 matrix segment. This is targeting 4.3 (changes here could mess with scripts people have) which will be dropping that version anyway (https://github.com/userfrosting/UserFrosting/pull/937) so in the grand scheme of things the build is green.

**Comment by lcharette** [comment]
> Ugh, build errors are caused by composer failing on the PHP v5.6 matrix segment. 

You can pull the latest fix for this from the `hotfix` branch

**Comment by Silic0nS0ldier** [comment]
`hotfix` has been integrated, fingers crossed the build works.

**Comment by Silic0nS0ldier** [comment]
CI failures are addressed in hotfix, and are related to fixes released for Assets that tripped up a faulty test.

**Comment by lcharette** [comment]
This targets 4.3.0 right ?

**Comment by Silic0nS0ldier** [comment]
> This targets 4.3.0 right ?

Yeah, it does. Be kinda rude to just break someones workflow in a seemingly minor release.

**Comment by Silic0nS0ldier** [comment]
Getting StyleCI happy is going to be tedious, especially since it appears to have some rules that are at odds with PHP CS Fixer. Out of scope for this IMO.

@lcharette you happy for this to be merged into dev?

**Comment by Silic0nS0ldier** [comment]
https://travis-ci.org/userfrosting/UserFrosting/jobs/522607680
Damn, I recall seeing this in a few previous builds as well.

**Comment by Silic0nS0ldier** [comment]
An intermittent failure. Lovely.

**Comment by lcharette** [comment]
> Getting StyleCI happy is going to be tedious, especially since it appears to have some rules that are at odds with PHP CS Fixer. Out of scope for this IMO.
> 
> @lcharette you happy for this to be merged into dev?

CS Fixer rules are as close as I could get them to default StyleCI on, but there's still some missing on CS-Fixer side to be exact same match. Hotfix branch should be fine on styling, so until we merge hotfix into develop, and sync back this PR with develop, error should be expected. Not sure how safe it will be to merge with the partial update from Master? 

Meanwhile, I restarted the failing test

**Pull request merged**
