### PR TITLE
Add missing lines of Thai language

### PR DESCRIPTION
**Pull request by popiazaza**

### CODE REVIEW

**Comment by r3wt** [comment]
looks ok to me.

@alexweissman @Netrilix All in favor of merging?

**Comment by Netrilix** [comment]
I'm in favor

**Comment by alexweissman** [comment]
I can't read Thai, but this looks good to me.  Can we add this in with the next hotfix instead of merging it directly?

**Comment by Netrilix** [comment]
Yeah, I'll add it to the list.

**Comment by alexweissman** [comment]
Great.  This way, we can merge everything into both the master and dev branches.

**Comment by Netrilix** [comment]
This was merged into `hotfix-0.3.1.12`, which should be merged into `master` in the next day or so.

**Pull request closed without merging**
