### PR TITLE
Update AdminLTE to 2.4.15

### PR DESCRIPTION
**Pull request by amosfolz**
Will need help identifying if anything in `AdminLTE-custom.js` that I removed is actually still needed. (As far as I can tell, it is not)

issue #994

### CODE REVIEW

**Comment by amosfolz** [comment]
I just looked this over and manually tested again. Pending if @lcharette can remember what [these lines](https://github.com/userfrosting/UserFrosting/blob/master/app/sprinkles/core/assets/userfrosting/js/AdminLTE-custom.js#L17-L71) were meant to fix, this is ready for merge.

**Comment by lcharette** [comment]
> Pending if @lcharette can remember what [these lines](https://github.com/userfrosting/UserFrosting/blob/master/app/sprinkles/core/assets/userfrosting/js/AdminLTE-custom.js#L17-L71) were meant to fix, this is ready for merge.

https://github.com/userfrosting/UserFrosting/blob/master/app/sprinkles/core/assets/userfrosting/js/AdminLTE-custom.js#L59

> Overwrite here. Otherwise, the menu href based active will be removed

Not sure what that meant, but I believe it's linked to nested entries in the nav menu. Might be something that's been solved in newer version of AdminLTE.

**Comment by amosfolz** [comment]
Just means I can not tell (or don't know how to figure out) what that code was meant to do.

**Comment by amosfolz** [comment]
Okay, I'll test out a nested menu to make sure it's working right.

**Comment by amosfolz** [comment]
Just putting this here for reference https://adminlte.io/docs/2.4/upgrade-guide

**Comment by amosfolz** [comment]
I tested the tree-view and everything worked OK.

**Comment by lcharette** [comment]
They are making fun of you !

https://github.com/ColorlibHQ/AdminLTE/releases/tag/v2.4.15

**Comment by lcharette** [comment]
Alright, let's freeze it on 2.4.15 for now

**Pull request merged**
