### PR TITLE
Improve ordering by activity date

### PR DESCRIPTION
**Pull request by ktecho**
Some activity logs can occur at the same second, so ordering just by date can show the results unordered. As per @lcharette suggestion, we can order by `occurred_at` AND `id`. That should gives better results.

### CODE REVIEW

**Comment by lcharette** [comment]
The style issue will need to be updated first : https://github.styleci.io/analyses/OML5Lk?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by ktecho** [comment]
@lcharette I re-added the whitespace but it's giving two fails. Do you know what could be happening?

**Comment by lcharette** [comment]
Nan, you need to remove the whitespace. 

FYI, Codecov failure can be ignored

**Comment by ktecho** [comment]
@lcharette Should be done now

**Pull request merged**
