### PR TITLE
Misc. improvements to assets pipeline

### PR DESCRIPTION
**Pull request by Silic0nS0ldier**
* Type validation of build scripts
* Removed redundant properties from in-box bundle definitions
* Bumped `jquery-validation` and `urijs` up to bring in vulnerability fixes
* Split gulp logger adapter into its own package
* Improved handling of multi-line log items
* Native ESM (asset processing starts much more quickly, this extends to many direct dependencies)
* Typo swatting
* Updating placeholder image URLs (old service now redirects, placeholders failed to render)
* Updates NodeJS versions in CI to use newest version in major version range
  All versions save for the newest in a given supported major NodeJS release is effectively end of life. While we aim for compatibility across an entire major version line, it is impractical to enforce this in CI since it means running ancient versions which may be full of vulnerabilities, bugs and subtle behaviour changes (e.g. CJS module imports having named import support introduced)..

This is mostly complete, remaining work includes;
- [x] Release 1.0.0 of `gulp-prune`
- [x] Release 1.0.0 of `@userfrosting/ts-log-adapter-gulplog`

### CODE REVIEW

**Review by lcharette — APPROVED** [review]
LGTM so far

**Comment by lcharette** [comment]
@Silic0nS0ldier Any news on this ?

**Comment by Silic0nS0ldier** [comment]
Totally forgot about this, thanks for the poke. I'll try and get this finished this week.

**Comment by Silic0nS0ldier** [comment]
```
file:///home/runner/work/UserFrosting/UserFrosting/build/node_modules/@userfrosting/merge-package-dependencies/dist/exceptions.js:2
import { LogicalException } from "node-exceptions";
         ^^^^^^^^^^^^^^^^
SyntaxError: The requested module 'node-exceptions' does not provide an export named 'LogicalException'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:92:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:107:20)
    at async Loader.import (internal/modules/esm/loader.js:179:24)
```
So _close_! Damn subtle ESM behaviour differences. Odd that this wasn't picked up by the package CI.

**Comment by Silic0nS0ldier** [comment]
Twas because we were using ancient versions of NodeJS lines. 12, 14 and 16 are all currently supported however it is impractical to be testing against the minimum version of a given major line. Given how software support works (the creation of new versions with issues resolved), it doesn't make sense to be using the minimum version. I've unpinned the NodeJS versions in the CI to address this issue.

**Review by lcharette — APPROVED** [review]

**Comment by lcharette** [comment]
For some reason, I had this marked for `hotfix`, but it's already in sync with `develop`... I guess I'll merge in develop for 4.6 then  ¯\_(ツ)_/¯

**Pull request merged**
