### PR TITLE
Hotfix sr rs

### PR DESCRIPTION
**Pull request by zbigcheese**
Serbian translations for the base sprinkles

### CODE REVIEW

**Comment by lcharette** [comment]
Can you add `sr_RS` to the default config file ?

**Comment by amosfolz** [comment]
I'm not sure where in the order this one should go... Config says to list in order according to https://en.wikipedia.org/wiki/List_of_languages_by_total_number_of_speakers

**Comment by lcharette** [comment]
At this point, Alphabetically is probably easier for people to find in a dropdown. @alexweissman ?

**Comment by lcharette** [comment]
Actually, with the planned changes in 4.4 and 5.0, the list will probably be alphabetical as it will be dynamically loaded or user defined in the config...

**Pull request merged**
