### PR TITLE
Asset pipeline optimisations

### PR DESCRIPTION
**Pull request by Silic0nS0ldier**
This PR revises how assets are processed, specifically by handling the virtual path logic up-front and before we read files into memory.

### Remaining Work
- [x] Include log level in log adapter
- [x] Uniquely identify log sources in log adapter
- [x] Use constants for common paths
- [x] Finalise and release @userfrosting/gulp-bundle-assets
- [x] Finalise and release @userfrosting/vinyl-fs-vpath
- [-] Move minification to pipeline using `gulp-if` - Not possible without major refactor and breaking changes, to be considered later.

### Benchmarks

These benchmarks are not performed on an isolated machine so results may vary. All benchmarks are performed at idle to ensure some level of consistency.

#### 2020.02.19

_OS: Windows 10 2004 19564.1005 64bit_
_RAM: 16GB_
_Storage: SSD_
_CPU: i7-6700 Quad Core 3.4GHz_
_Shell: PowerShell 6.2.1_

`master`: 53s
This PR: 27s

Improvement: 49%

#### 2020.02.23

_OS: Windows 10 2004 19564.1005 64bit_
_RAM: 16GB_
_Storage: SSD_
_CPU: i7-6700 Quad Core 3.4GHz_
_Shell: PowerShell 6.2.1_

`master`: 54s
This PR: 34s

Improvement: 37%

#### 2020.03.14

_OS: Windows 10 2004 19577.1000 64bit_
_RAM: 16GB_
_Storage: SSD_
_CPU: i7-6700 Quad Core 3.4GHz_
_Shell: PowerShell 6.2.1_

`master`: 80s
This PR: 53s

Improvement: 34%

_OS: MacOS 10.14.6_
_RAM: 16GB_
_Storage: SSD_
_CPU: i5-3210M Dual Core 2.5GHz_
_Shell: PowerShell 6.2.1_

Results inconsistent

_OS: Windows 10 2004 19577.1000 64bit - WSL2 Ubuntu 18.04_
_RAM: 16GB_
_Storage: SSD, files outside WSL2 VM disk_
_CPU: i7-6700 Quad Core 3.4GHz_
_Shell: Bash 4.4.20_

`master`: 327s
This PR: 154s

Improvement: 52%

### CODE REVIEW

**Comment by ktecho** [comment]
@Silic0nS0ldier Looking forward to test it, as I've been hit by the bug that adds this to .svg images:

`//# sourceMappingURL=apachekafka.svg.map`

**Comment by Silic0nS0ldier** [comment]
@ktecho Thanks for the reminder, I'd forgotten about that. Good news is it'll be trivial to implement the necessary changes thanks to the refactor, should provide some more performance gains as well since the bundler will have a lot less files to check.

**Comment by ktecho** [comment]
@Silic0nS0ldier I'm glad my message served to remind you about it :)

Looking forward to test the speed improvements too. Today I compiled the first version of a not so big sprinkle and it lasted for some time :)

**Comment by Silic0nS0ldier** [comment]
I've just pushed up some changes that I believe should fix the sourcemaps in SVG files problem.

**Comment by ktecho** [comment]
@Silic0nS0ldier Great! That was fast!

**Comment by lcharette** [comment]
> @Silic0nS0ldier Looking forward to test it, as I've been hit by the bug that adds this to .svg images:
> 
> `//# sourceMappingURL=apachekafka.svg.map`

Related to this? https://github.com/userfrosting/UserFrosting/issues/985

**Comment by ktecho** [comment]
Yes, indeed.

**Comment by Silic0nS0ldier** [comment]
Ready for review/testing. Packages will be finalised once everything is green.

**Comment by lcharette** [comment]
Restarted the false negative test

**Comment by Silic0nS0ldier** [comment]
Tested locally. Ended up identifying 2 issues which have now been resolved.

1. `bundle.result.json` having absolute paths, resolved with `path.relative` function and forcing slashes to always be forward.
2. Sign in page not redirecting to dashboard on logic, resolved by removing browserify support when it turns out was completely broken since day zero. ¯\_(ツ)_/¯

**Comment by Silic0nS0ldier** [comment]
Figured out a way to bring back browserify without the issues. Even actually exposes the APIs now. I'll have this reintroduced shortly.

**Comment by Silic0nS0ldier** [comment]
Browserify support is back, and working as advertised this time. All dependencies are released as stable versions. This is ready for review.

**Pull request merged**
