### PR TITLE
Update install.php

### PR DESCRIPTION
**Pull request by x00x70**
make 'Y' the default behaviour for STDIN

### CODE REVIEW

**Comment by Silic0nS0ldier** [comment]
LGTM, but it could use some way to indicate the default action.
Especially since this will invert behaviour.

**Comment by x00x70** [comment]
Yeah - i thought that as 'Y' was uppercase this indicates it is the default (as per most unix programmes). see - http://askubuntu.com/a/322601

**Comment by Silic0nS0ldier** [comment]
Windows background. :wink: PowerShell is much more verbose with Yes/No scenarios, and command prompt rarely has a Yes/No scenario.

Either way, good to know.

**Comment by Silic0nS0ldier** [comment]
(personally though, I quite like the `([y]/n)` version, if only because its hard to miss)

**Comment by x00x70** [comment]
done.

**Comment by Silic0nS0ldier** [comment]
Cheers. Should make the behaviour much more apparent to the user base (and prevent me from making mistakes when I'm tired).

**Pull request merged**
