### PR TITLE
reworked flashAlerts(), client-side pushAlert(), clearAlerts()

### PR DESCRIPTION
**Pull request by thexmanxyz**
As discussed in chat ;) but for the notes!

The existing alerting functionality has been extended to allow the client-side message notification via JQuery. The old functionality is preserved and was tested. Therefore, it is now possible to simply push an alert on any JQuery element with the function `pushAlert(alert_type, alert_message)`. Existing alerts can be easily removed with `clearAlerts()`. Everything concerning server-side alerts should work as before. 

There are now two additional helper functions (`getAlertHtml(..)`) which were necessary to prevent the unnecessary doubling of code. So both functions (`pushAlert(), flashAlerts()`) are built on the same sub functions.

**Edited: updated Results**

### CODE REVIEW

**Comment by alexweissman** [comment]
Nice, thanks!  Do you think we could combine these into a single plugin?  Then we could do something like:

```
$('#alerts').flashAlerts();   // Just initializes the plugin on the '#alerts' element
$('#alerts').fetch();            // Grabs server-side alerts (but doesn't render them yet)
$('#alerts').push('danger', 'something terrible!'); // Manually add a alert (but doesn't render them yet)
$('#alerts').render();         // Renders all alerts
```

I guess this would be a breaking change, but perhaps for v4 this would be useful.

**Comment by thexmanxyz** [comment]
No problem! Ok I understand how this should work in the end :). But I don't exactly know right now how to store the fetch()-ed and push()-ed alerts before rendering it to the UI. Maybe you have already and idea, i guess the rest should no problem!

**Comment by alexweissman** [comment]
So basically, instead of rendering them immediately, the plugin would store them in a private member variable.  See, for example, this jQuery plugin template: https://gist.github.com/Air-Craft/1300890

That way you would have an opportunity to modify the messages, add/remove messages, etc before rendering them to the DOM.

**Comment by Netrilix** [comment]
Before we merge this, could you add a line to the changelog about it? This is the first change of this hotfix, so there's already a `-` line ready for you to type on (just look down to a previous hotfix to get a feel for how we title stuff).

**Comment by thexmanxyz** [comment]
@Netrilix Sorry about the dumb question, but I don't exactly know what I mean. I'm quite new to Git so I'm no really sure what you mean :). Sorry on that. But if i know what you want from me I will of course do it :)

**Comment by Netrilix** [comment]
@thexmanxyz Find this file: https://github.com/userfrosting/UserFrosting/blob/master/CHANGELOG.md in your repository... if it's already got the `0.3.1.20` header there, you can just add your comment on the line that starts with a dash. If not, you'll have to pull `hotfix-development` into your branch (the same way you did with `0.3.1.18` and `0.3.1.19` above) first, then it should show up.

**Comment by thexmanxyz** [comment]
@Netrilix local and remote the last revision listed in the changelod.md is 0.3.1.19. I have to ask again sorry. So you simply mean to "git pull origin hotfix-development" change the dash line under 0.3.1.20 with an appropriate comment? And then push it? Argh sorry, I dont want to do anything wrong :D. I'm really a Git noob...what i did until now:

- forked
- cloned my repo
- added the file
- commit 
- and pushed it with git push origin master
- after that the Pull Request

**Comment by Netrilix** [comment]
Yep, exactly as you described. Pull the hotfix-development branch in, and you'll see that change in the changelog so you can add your comment.

**Comment by thexmanxyz** [comment]
@Netrilix Pulled the hotfix-development branch, modified the line and pushed it back, hope that was ok :)

**Comment by thexmanxyz** [comment]
@Netrilix Everythings ok :), I want to do everything right and I'm motivated to learn new things. So it's better to ask a stupid question instead of doing it wrong, over and over again. So it's fine, when someone tell me how to do it right! Thanks for your patience! So the problem with my first pull was that i took the master instead of the hotfix-development branch? So your two merge branch lines were included in my Pull Request. I was wondering on that after I created it!

**Comment by Netrilix** [comment]
@thexmanxyz Yeah, basically here's what will happen:

- Someone makes edits to the `hotfix-development` `CHANGELOG.md` file.
- You pull the `master` branch.
- You make your changes to whichever files and `CHANGELOG.md`.
- You make a PR to `hotfix-development`.
- Now, your PR's `CHANGELOG.md` conflicts with the `hotfix-development` `CHANGELOG.md`, so they have to be manually merged together.

By pulling from `hotfix-development` before you push the PR, you've avoided that conflict on the last step.

Hope that made sense the way I described it!

**Comment by thexmanxyz** [comment]
Yeah it makes sense to me. I understand the problem that occured / can occur. I've done lots of stuff with svn but literally nothing with git until today. So the commands, workflow and stuff are completely new for me. 

My last question, for today ;), when I add the changes which @alexweissman proposed, i do again a pull `hotfix-development`, add the changes to the `CHANGELOG.md`, `add` the modified file(s), `commit` them and `push` them to my master right? When this PR is closed I have to open a new one? That would be the correct course of action? If yes everything makes sense :)

**Comment by Netrilix** [comment]
Well, the changes that he proposed are for Version 4, so he'd probably want them somewhere else (since they'll break existing code running Version 0.3.1).

But speaking hypothetically, you could add them right to the same PR and just change the line you added to the change log while the PR is still open (since we're still talking about the same feature), or you could make a new PR and a new line in the change log if the PR had already been closed (since the feature had already been finalized and you're now making changes to it).

**Comment by thexmanxyz** [comment]
@Netrilix Thanks again for your patience. Ok I understand how this should work. Yeah of course I didn't mind that this change breaks the code of the current version, so it have to be in v4. Fine I've learned a lot today, thanks!

How do i prevent that a change on a File that I want to `push`, goes directly to an open PR? When I do another change like I did it for the `CHANGELOG.md` and the `userfrosting.js` it will be listed here in this PR. I have to stop asking questions :D 

@alexweissman I keep an eye on your suggested changes and come back to you as soon as I have an suitable solution. Thanks also for the Link on the Plugin (Air-Craft) I will take that into account when implementing the functionality!

**Comment by Netrilix** [comment]
@thexmanxyz In the future, when you make PRs, create a separate branch (at the same point your `master` is at) and then PR the new branch instead of `master`. That'll make the PR track your feature branch instead of `master`, and you can go on committing to your `master` without issue.

**Comment by Netrilix** [comment]
I tested this and it works as advertised. However, do you have any thoughts about appending instead of overwriting? Right now, if you throw two alerts in a row, the first disappears in favor of the second, instantly if they're both thrown at the same time.

**Comment by thexmanxyz** [comment]
@Netrilix So for every PR ("set of features" - that belongs together) a seperate personal branch would be the correct way? And i can have multiple of them seperately in parallel all on different PRs for one Project? Ok nice, thanks for the explanation. I will soon take a closer look on all the important features that are part of git so that I'm confident for future participations and in my own interest.

Don't worry about tying my current `master` branch. You also found an useful extension for the pushAlert functionality, which i didn't mind. I already know how to do this, i will adapt the functionality and push it. Nice that the code is working.

- I simply check the `inner html` of the `userfrosting-alerts` `div`, if it's empty, simple set it, otherwise, append the message. I don't think there should be any interferences which keeps stacking them up unintentional high in count or that there is some other stuff in the `div `which should not.

But when talking about stacking, one thing that I have to throw in, is the presentation of the alerts, generally. I think about grouping them together in some way and present them in a more fancy way. If you geht like four in a row it looks quite like an overflow for the user. In a general use, a lot of this stuff is of couse intercepted if the validation on the client-side and directly thrown out on the ui elements, if the developer implements it right or minds it but it would be even though quite useful!

**Comment by Netrilix** [comment]
Okay, so does this make sense:

- Create a `clearAlerts()` function
- Stack alerts until the `clearAlerts()` is called
- Only change the type of message if the new message is more severe than the previous one
- Clear the type of message when clearing messages

**Comment by thexmanxyz** [comment]
Mhm do we really need an `clearAlerts()` for the simple stacking of `pushAlerts()` i don't think so. For the v4 it maybe useful or in general to have that function. But I can imagine a way that they can't stack up further then now, but if it's meant to be it will of course be possible.

I understand the alert-levels but I don't know were it belongs to. To the discussed quick change for stacking up `pushAlerts()` or generally on alerts (grouping ,v4).

ps.: i'm testing the changes for stacking push

**Comment by lcharette** [comment]
Hum, I haven't really followed the whole conversation, but `clearAlerts()` would remove the alerts from the DOM? Then it could be useful when submitting a form for example. You submit, then a validation error occur and display it. You submit again, but before displaying the same error, you `clearAlerts()` to start fresh?

**Comment by Netrilix** [comment]
That stacking looks awesome. I was thinking stacking inside the same alert div, but separate messages looks a lot better.

**Comment by thexmanxyz** [comment]
For a quick fix, it should of course look like as it did and how i made it with the recent push. But I imagine something fancy which maybe outlines the number of alers (or maybe the first alert) and allows the user to open the "hidden" alerts. This is nothing for now, but for the future. I think it's useful and less space consuming. But i will of course align with your decisions.

**Comment by Netrilix** [comment]
I'm happy to merge your code in the way it is now, but I'd imagine someone will want to add in the clear function at some point in the future. @lcharette 's comment is a great example of when the clear would be used.

**Comment by thexmanxyz** [comment]
`clearAlerts()` comming soon! :P

**Comment by Netrilix** [comment]
That last push works beautifully!

**Comment by thexmanxyz** [comment]
Nice thanks! I will think about the further changes tomorrow, time to sleep here in austria 4AM :P

**Comment by thexmanxyz** [comment]
@Netrilix The bug with undefined is now fixed, but I actually don't know why `alert_message` turns undefined in the function after passing. When passing `alert_message['type']`, `alert_message['message']` everythings fine. I can imagine some reasons but i don't know which applies to js.

**Comment by alexweissman** [comment]
What's the story with this?  I'm looking into working on the v4 alerts plugin.

**Comment by Netrilix** [comment]
I wanted to test it more after he fixed that last bug, but I haven't had time.

**Comment by thexmanxyz** [comment]
I'm using the new functionalit0 in my project but I didn't experience a problem after the last fix :) just to let you know

**Pull request merged**
