### PR TITLE
Fix for PostgreSQL setup

### PR DESCRIPTION
**Pull request by x00x70**
Stops charset errors at setup.

### CODE REVIEW

**Comment by alexweissman** [comment]
`charset` should get pulled from the DB config rather than being hardcoded.

**Comment by x00x70** [comment]
agree - just need bakery to read full config then ;)

**Comment by alexweissman** [comment]
Alright, leaving this to you and @lcharette.  Taking this off the 4.1.3 roster.

**Comment by lcharette** [comment]
Should be good to go. @x00x70 can you test to make sure it still works with Postgre? Should be fine with MySQL ;)

**Comment by x00x70** [comment]
Tested and confirmed for PostgreSQL 9.6.2

**Pull request merged**
