### PR TITLE
Hotfix development/added rtl support

### PR DESCRIPTION
**Pull request by aminakbari**
I added support for right-to-left languages for AdminLTE. All text will be written from right to left. Special CSS files will be imported from assest if the chosen language is right to left.

### CODE REVIEW

**Comment by lcharette** [comment]
I'm not a big fan of https://github.com/userfrosting/UserFrosting/pull/817/files#diff-2f859228e39382fd31e49102c1e5162eR32, but I guess for now it will do. A more permanent solution would be to [use metadata](https://chat.userfrosting.com/channel/general?msg=CiJ2Y3ApHiMb4rGjE), but this needs to be compatible with #672. Also related to https://github.com/userfrosting/i18n/issues/4


This is a direct fix for #637

**Comment by aminakbari** [comment]
Me neither. What we could be using for now is also to check if `translate("RTL")` is set or not.
Then, RTL languages only have to add a `"RTL" => "TRUE"` to their locale file.

**Comment by lcharette** [comment]
That would indeed be sexier in the mean time. Can you open another issue for the metadata thing?

**Comment by alexweissman** [comment]
There is one open in `i18n`: https://github.com/userfrosting/i18n/issues/4

**Comment by alexweissman** [comment]
Gonna hold off on this until it gets cleaned up a little more.

**Pull request closed without merging**
