### PR TITLE
optional enable twig cache

### PR DESCRIPTION
**Pull request by blink01**
Works great for me. I'm eager to here you feedback.

### CODE REVIEW

**Comment by Netrilix** [comment]
I just confirmed the Twig will create the `cache` folder if it doesn't already exist, so there's no additional configuration required there.

**Comment by r3wt** [comment]
@frostbitten that needs to be reverted IMO. If the dir is not owned by the webserver user, twig will die with a fatal error. 

Checks need to be performed to ensure webserver owns the directory or has permission to write to the directory. if it doesnt we should either:

a) throw exception
b) silently ignore directive and write to error log indicating that cacheing is disabled due to permissions/ownership error.

**Comment by alexweissman** [comment]
Yes, I agree with @r3wt .  Also, any change to the code should also include an update to the changelog and version number in the DB.

**Comment by Netrilix** [comment]
Nice catch @r3wt . I thought of the directory not existing, but not of it not being accessible at all.

**Comment by r3wt** [comment]
No prob, i just happened to be in the neighborhood and recalling an embarrassing production issue from days gone by lol

**Comment by frostbitten** [comment]
Ah, okay. Sorry for that, didn't go over the pr checklist. Haven't looked into how twig does it, but if it uses mkdir shoudln't the created folder be guaranteed to be 0777?

**Comment by alexweissman** [comment]
Yes, but PHP will still need permission for the parent directory.

**Comment by Netrilix** [comment]
We'll also have to look into the scenario where the directory itself *does* exist, but isn't writable.

**Pull request merged**
