### PR TITLE
Azure SQL Server and SQL Server Support

### PR DESCRIPTION
**Pull request by Silic0nS0ldier**
Azure SQL Server and SQL Server Support as discussed in  https://github.com/userfrosting/UserFrosting/issues/541.

Tested with Azure SQL Server (site hosted in localhost, database at Microsoft Azure) and MySQL/MariaDB in localhost.

### CODE REVIEW

**Comment by alexweissman** [comment]
Looking good - but what's the issue in `InstallController`?  Why was that `save()` giving you trouble?  It doesn't seem to set the `id` explicitly anywhere.

**Comment by Silic0nS0ldier** [comment]
See line 234 of the install controller.

**Comment by alexweissman** [comment]
Oh!  So, trying to set the `id` through Eloquent's active record is giving you the same problem?

I assume the issue is with:

`$user->id = $this->_app->config('user_id_master');`

**Comment by Silic0nS0ldier** [comment]
Yep. Hence me putting in the raw T-SQL statements for when its Sql Server. I tried enabling the id specification before it, but no luck as is server considered them to be different sessions (and the necessary setting resets to default once the session ends).

**Comment by alexweissman** [comment]
Gotcha.  This is fine as a workaround for now, but we should use parameter binding instead of interpolating variables in the query, since this opens you up to SQL injection.

**Comment by Silic0nS0ldier** [comment]
You mean like described at http://www.w3schools.com/php/php_mysql_prepared_statements.asp ?

**Comment by alexweissman** [comment]
Yep!  But in Laravel, it is exposed via the `setBindings` method.  See http://stackoverflow.com/a/20873009/2970321

Actually, you probably don't even need that level of control - why not just use `insert`?  Then you could convert the user data to an array using `toArray()` and just pass it into the call to `insert`.

**Comment by Silic0nS0ldier** [comment]
Took a ludicrous amount of googling and testing, but I've got it working.

Something I did stumble upon something else though, it seems that the JS and CSS minification is busted.

**Comment by alexweissman** [comment]
So, maybe a silly question, but...couldn't you just call the `SET IDENTITY_INSERT [$tableName] ON;` query, and then use `->save()` like normal, instead of having to add that explicit insert query afterwards?

**Comment by Silic0nS0ldier** [comment]
If only. The trouble is that it would be considered a different session, and as such SQL Server resets the `IDENTITY_INSERT` variable to default before you can call `->save()`. In the end, this was the cleanest I could get it.

But who knows? Maybe the people who work on the ORM library will do something nice in the future, like providing a way to allow easy specification of an identity in SQL Server. Probably not though, given that PHP + SQL Server is a rare combo.

**Comment by alexweissman** [comment]
What if you tried using a [database transaction](https://laravel.com/docs/5.2/database#database-transactions)?  That might keep the session open...

**Comment by Silic0nS0ldier** [comment]
Did try transactions (if you look at the first commit, you'll see that I forgot to remove one after attempting that approach).

All transaction does is make it easy to rollback changes. Each interaction with the database is still treated as its own session.

**Comment by alexweissman** [comment]
Weird.  Ok, I'll test this and hopefully get it pulled in!

**Comment by alexweissman** [comment]
Ok, a couple of things:

1. You should use Carbon for the date (`\Carbon\Carbon::now();`) instead of PHP's native `date` function.
2. In your custom logic block for SQL server, the root user doesn't get added to the default groups.  I think this is because you reload the `$user` object after the groups have been added.

**Comment by Silic0nS0ldier** [comment]
Not sure how I missed the default groups. Nevertheless, it should all be good now.

**Comment by lcharette** [comment]
Looks like this introduced a bug. See : https://github.com/userfrosting/UserFrosting/commit/5f3cb538ed4086f9afc71758c2e2ee53d533f7e3#commitcomment-20142743

**Pull request merged**
